# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.10
  hooks:
    - id: insert-license
      args: [--license-filepath, LICENSE]
      types: [python]
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v1.19.0
  hooks:
    - id: setup-cfg-fmt
- repo: https://github.com/PyCQA/isort
  rev: 5.10.0
  hooks:
    - id: isort
- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
    - id: autoflake
      args: [--in-place, --remove-unused-variables, --remove-all-unused-imports, --remove-duplicate-keys]
- repo: https://github.com/python/black
  rev: 21.10b0
  hooks:
    - id: black
    - id: black
      name: black (pyi)
      types: [pyi]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
    - id: mypy
      name: mypy36
      language_version: python3.6
      additional_dependencies:
        - importlib_resources>=3.3.0
        - types-requests
    - id: mypy
      name: mypy37
      language_version: python3.7
      additional_dependencies:
        - importlib_resources>=3.3.0
        - types-requests
    - id: mypy
      name: mypy38
      language_version: python3.8
      additional_dependencies:
        - importlib_resources>=3.3.0
        - types-requests
    - id: mypy
      name: mypy39
      language_version: python3.9
      additional_dependencies:
        - importlib_resources>=3.3.0
        - types-requests
- repo: https://gitlab.com/pycqa/flake8.git
  rev: 3.9.2
  hooks:
    - id: flake8
      name: flake8_36
      language_version: python3.6
      additional_dependencies: [flake8-2020, flake8-bugbear, flake8-comprehensions, flake8-logging-format, flake8-mutable, pep8-naming, flake8-tidy-imports, flake8-annotations-coverage]
    - id: flake8
      name: flake8_37
      language_version: python3.7
      additional_dependencies: [flake8-2020, flake8-bugbear, flake8-comprehensions, flake8-logging-format, flake8-mutable, pep8-naming, flake8-tidy-imports, flake8-annotations-coverage]
    - id: flake8
      name: flake8_38
      language_version: python3.8
      additional_dependencies: [flake8-2020, flake8-bugbear, flake8-comprehensions, flake8-logging-format, flake8-mutable, pep8-naming, flake8-tidy-imports, flake8-annotations-coverage]
    - id: flake8
      name: flake8_39
      language_version: python3.9
      additional_dependencies: [flake8-2020, flake8-bugbear, flake8-comprehensions, flake8-logging-format, flake8-mutable, pep8-naming, flake8-tidy-imports, flake8-annotations-coverage]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-yaml
    - id: check-toml
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
